apiVersion: apps/v1 # Menentukan versi API yang digunakan (apps/v1 dalam kasus ini).
kind: Deployment # Mendefinisikan bahwa YAML ini menggambarkan sebuah Deployment Kubernetes.
metadata:
  name: shipping-service-deploy # Nama Deployment untuk shipping-service-deploy
spec:
  replicas: 1 # Jumlah replika yang diinginkan untuk shipping-service
  selector:
    matchLabels:
      app: shipping-service # Label pemilih untuk aplikasi shipping-service
  template:
    metadata:
      labels:
        app: shipping-service # Label untuk aplikasi shipping-service
    spec:
      containers:
        - name: shipping-service # Nama kontainer untuk shipping-service
          image: ghcr.io/risqikhoirul/shipping-service:latest # Gambar kontainer untuk shipping-service
          ports:
            - containerPort: 3001 # Port tempat kontainer layanan pengiriman mendengarkan
          env:
            - name: AMQP_PASSWORD # Variabel lingkungan untuk kata sandi AMQP
              valueFrom:
                secretKeyRef:
                  name: my-rabbitmq # Nama Secret untuk kredensial RabbitMQ
                  key: rabbitmq-password # Kunci Secret untuk kata sandi RabbitMQ
            - name: AMQP_URL # Variabel lingkungan untuk URL AMQP
              value: "amqp://user:$(AMQP_PASSWORD)@my-rabbitmq:5672" # Nilai untuk URL AMQP
